/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface EnhancedVideoHtml {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface EnhancedVideoHtmlAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'EnhancedVideoHtml': Components.EnhancedVideoHtml;
  }

  interface StencilIntrinsicElements {
    'enhanced-video-html': Components.EnhancedVideoHtmlAttributes;
  }


  interface HTMLEnhancedVideoHtmlElement extends Components.EnhancedVideoHtml, HTMLStencilElement {}
  var HTMLEnhancedVideoHtmlElement: {
    prototype: HTMLEnhancedVideoHtmlElement;
    new (): HTMLEnhancedVideoHtmlElement;
  };

  interface HTMLElementTagNameMap {
    'enhanced-video-html': HTMLEnhancedVideoHtmlElement
  }

  interface ElementTagNameMap {
    'enhanced-video-html': HTMLEnhancedVideoHtmlElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
